name: Build Geode mod

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build mod
        id: build
        uses: geode-sdk/build-geode-mod@main

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: anymenu-mod
          path: ${{ steps.build.outputs.build-output }}